### ISSUE TITLE
Plots without prediction

### ISSUE THREAD

**Issue by Binbose** [quancore/social-lstm#1]
After running the visualize script, a lot of plots are generated. However, in most of them no prediction trajectory is plotted, for example here.
![sequence00008](https://user-images.githubusercontent.com/25252778/45463146-dbf3d900-b6bf-11e8-9d58-10685f9beadd.png)

What is the reason for that?

**Comment by quancore** [comment]
In the project, usually, there are lots of peds in a one windows (20 frames) which led to be a mess. Therefore, I disabled to plot predicted trajectory for non-target ped in a windows (target ped in a window means we have data about this ped and we are trying to predict it )

**Comment by Binbose** [comment]
Target pedestrian means, it is in the test set?

Is there a way to only plot predicitons? Because those seem to be the only interesting ones.

**Comment by quancore** [comment]
Target pedestrian means the pedestrian we are trying to predict its trajectory currently (for given 20 frames) in the test set.
https://github.com/quancore/social-lstm/blob/56a9b72607a2fb4c7fa16dfe6a9032411fcab13d/visualize.py#L394
As you can see, filtered_true_x and  filtered_true_y are the coordinates of prediction so you can modify (exchange) the line of 
https://github.com/quancore/social-lstm/blob/56a9b72607a2fb4c7fa16dfe6a9032411fcab13d/visualize.py#L401
with the mentioned line to plot only predicted trajs.
