### ISSUE TITLE
about the train loss

### ISSUE THREAD

**Issue by bbidong** [quancore/social-lstm#10]
In the training, i find the loss less than 0 sometimes. i guess the smaller the loss, the better(eg: loss=-10 is better than loss=-5).
Am i right ??  @quancore

**Comment by junjun520416** [comment]
> In the training, i find the loss less than 0 sometimes. i guess the smaller the loss, the better(eg: loss=-10 is better than loss=-5).
> Am i right ?? @quancore

sure  ,the reason of loss less than 0  is that -log(p|o,u p)
