### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Manojkumarjala** [quancore/social-lstm#14]
when i try to run train.py i'm getting error lie
![Screenshot from 2019-06-10 15-54-10](https://user-images.githubusercontent.com/29269504/59189605-1aa7b880-8b98-11e9-825d-245a54a8ef41.png)

Traceback (most recent call last):
  File "train.py", line 626, in <module>
    main()
  File "train.py", line 94, in main
    train(args)
  File "train.py", line 197, in train
    x, y, d , numPedsList, PedsList ,target_ids= dataloader.next_batch()
  File "/media/sdb/vish_features/dominant_flow/manoj/social-lstm-master/utils.py", line 424, in next_batch
    target_ids.append(self.target_ids[self.dataset_pointer][math.floor((self.frame_pointer)/self.seq_length)])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Can somebody help pls

**Comment by saranshvora** [comment]
Hi this is something to do with your dataset check your dataset whether it is similar to the dataset provided ... And also check for the predicted length of the dataset after the observed length whether it has '?' or numbers

**Comment by Manojkumarjala** [comment]
hello there i deleted the datasets and downloaded them again but same error is repeating

**Comment by quancore** [comment]
The dataset mainly used in the project is fetched from http://trajnet.epfl.ch/ so be careful about formatting.
