### ISSUE TITLE
MovieWriter stderr: Unknown encoder 'h264'

### ISSUE THREAD

**Issue by sowmyakavali** [quancore/social-lstm#17]
while running visualize.py file it showing this error.
![error2](https://user-images.githubusercontent.com/51850438/59916132-f53e6880-943b-11e9-8f42-38eeaa2d7c22.png)
please any one help me to solve this

**Comment by Guanwh** [comment]
@sowmyakavali  Hi, In about 18th line of the visualize.py is“from adjustText import adjust_text”，do you have adjustText.py ? Thank you!

**Comment by LIUSIMIN963** [comment]
I had same problem

**Comment by whosnk** [comment]
I have the same question
