### ISSUE TITLE
get wrong while running vlstm_train.py

### ISSUE THREAD

**Issue by li2dong4** [quancore/social-lstm#18]
hello, I try to run vlstm_train.py on my coumputer,win7amd64 & pytorch 0.4.1 & python 3.6, and there is an error telling '[WinError 193] %1 is not a valid Win32 application' in _winapi.CreateProcess. I change to virtual environment and this is the configuration: win7 32bit & python36 &pythorch 0.4.1. But another error occurs:'DLL load failed' in 'from torch._C import *', it seems that pytorch can't work on windows 32bit. Did you met this problem?

**Comment by quancore** [comment]
The codebase has been developed on Ubuntu so it is highly probable that not working on Windows.
