### ISSUE TITLE
Prediction not autoregressive?

### ISSUE THREAD

**Issue by Binbose** [quancore/social-lstm#2]
During sampling of future trajectories, it seems like the the ground truth is fed back into the network, not the predicted point, so the network is not autoregressive. Is that correct? Below is the code line I am referring to.

https://github.com/quancore/social-lstm/blob/56a9b72607a2fb4c7fa16dfe6a9032411fcab13d/helper.py#L459

**Comment by quancore** [comment]
For the validation sampling, yes this is the case. I was using the ground truth for prediction because of availability. However, you can change autoregressive manner as well.

**Comment by Binbose** [comment]
If I change it to a autoregressive behavior (basically just exchanging x_seq with ret_x_seq), the output becomes very unstable though and doesn't really makes sense anymore (training and running everything with your default settings). Were you able to achieve good results in an autoregressive mode?

**Comment by Binbose** [comment]
Hm, I trained it with the default settings (batch size 5 epochs 30), and it seems to not really work. Are the number of epochs in the default setting sufficient for you to get good results, or do I have to increase them?

**Comment by quancore** [comment]
I am unable to reproduce the training session and I cannot decide to be working or not. However, default parameters should work for a good training. If not you can increase it.
