### ISSUE TITLE
Datasets process

### ISSUE THREAD

**Issue by taoja12** [quancore/social-lstm#21]
I would like to ask, how to deal with a data set so that it can be put into social LSTM for use?
For example, I have a sequence of images, and also have hand moving videos, how to deal with them?

**Comment by quancore** [comment]
If you checked the example datasets in the repo, you will see that the data is tabular and numeric. For each frame, the data includes all peds with the current position. Therefore, you need to label all peds with unique ids and extract positions for each frame using these unique ids, which is a very human dependent task.

**Comment by taoja12** [comment]
I want to ask, unlike multiple people appear in one frame at the same time , label appeared peds with unique ids. If there only appear one hand in every frame, whether the label needs to be changed? Or it should always going to be the same ID?

At 2019-10-30 21:24:14, "Baran Nama" <notifications@github.com> wrote:


If you checked the example datasets in the repo, you will see that the data is tabular and numeric. For each frame, the data includes all peds with the current position. Therefore, you need to label all peds with unique ids and extract positions for each frame using these unique ids, which is a very human dependent task.

**Comment by taoja12** [comment]
Sorry, specifically, there have 10 different hands comes from 10 person, but erery frame only show one hand, whether the label needs to be changed? Or it should always going to be the same ID?

**Comment by quancore** [comment]
The ped ids should be consistent among frames and should not change. If the peds is unidentifiable at same frames, take your best guess to label them.

**Comment by taoja12** [comment]
When I run your code, I got a mistake like 
'.../social-lstm/utils.py', line 423, in next_batch
self.target_ids[self.dataset_pointer][math.floor((self.frame_pointer)/self.seq_length)]
IndexError: only integers, slices(':'), ellipsis('...'), numpy.newaxis('None') and integer or boolean arrays are balid indices'.
 How should I do to solve it, I have search some answers. Some answers said that appeared because the parameter types does not match
