### ISSUE TITLE
error when run train.py

### ISSUE THREAD

**Issue by chun-chun123** [quancore/social-lstm#27]
Thanks a lot for your code.
But when I run the train.py,it occurs error as follows:
![image](https://user-images.githubusercontent.com/56161480/74293630-52de4700-4d76-11ea-9434-528c9dad67cd.png)
could you please tell me why?
Thanks a lot for your attention

**Comment by xxAna** [comment]
@chun-chun123 hi~I met the same problem. Have you solve it?

**Comment by tristankpka** [comment]
+1 I got the same problem
