### ISSUE TITLE
Results far off

### ISSUE THREAD

**Issue by Binbose** [quancore/social-lstm#3]
After training the network in its defeault mode and subsequently running test.py with the defeault parameter, the output at the end is:

```
Best iteration has been changed. Previous best iteration:  0 Error:  31.76620076238882
New best iteration :  1 Error:  tensor(2.6017e-09)
Iteration: 1  Total training (observed part) mean error of the model is  tensor(2.6017e-09)
Iteration: 1 Total training (observed part) final error of the model is  tensor(5.7770e-09)
Smallest error iteration: 1
```

31 and 2.6e-9 both are far away from the reported 1.3. How can that be?

**Comment by saranshvora** [comment]
Hi Binbose, even I am getting similar errors what do you suggest about it ?

**Comment by Binbose** [comment]
I moved on not using social-lstm.
Look at social-gan if you are looking for a trajectory prediction model with working code.

**Comment by bbidong** [comment]
@saranshvora hello!  I am getting similar errors too? Could we hava a talk ??

**Comment by saranshvora** [comment]
@bbidong yes I would love to because I am also not sure how to fix this issue

**Comment by bbidong** [comment]
@saranshvora Would you like to add my WeChat?  my WeChat is  15101119239

**Comment by saranshvora** [comment]
I cannot add you on wechat I am getting some error my wechat_id: wxid_h06uwoccrw4q22

**Comment by bbidong** [comment]
@saranshvora I cannot add you too, you can send me a massage by my phone number, then i tell you more detail.

**Comment by junjun520416** [comment]
> @saranshvora I cannot add you too, you can send me a massage by my phone number, then i tell you more detail.
my wechat is :junjun520416  QQ:1131605944

**Comment by hzzzzjzyq** [comment]
Is there no solution to this problem?
