### ISSUE TITLE
Error in calculation of grid 

### ISSUE THREAD

**Issue by huang-xx** [quancore/social-lstm#4]
In your  grid.py script, I believe  current_x and current_y coordinates are in world coordinate system, and they are in meters.
But, width_bound, height_bound don't have a unit, they are just fractions. (line 30)

So, they should not be added or subtracted. ( line 38 and 39). It doesn't mean anything.

**Comment by quancore** [comment]
The calculation logic has been deduced from the former repo implemented by one of the writer of paper.In general, the calculation is not logical however, in my case I am normalizing the x and y so it should not be so problematic. You can ask the original repo for the logic behind.
https://github.com/t2kasa/social_lstm_keras_tf/blob/0e6dc8611dea864adc8f253809d0475c6c264a36/grid.py#L55
https://github.com/fjhheras/social-lstm-tf/blob/71dbaa16db03378f30e5c5c68a68f49be8d43e5f/social_lstm/grid.py#L25
