### ISSUE TITLE
In the train,true sequece as input(20),why?

### ISSUE THREAD

**Issue by junjun520416** [quancore/social-lstm#7]
in the article,from time tobs+1 to tpreds,the author use the predicted position from the previous social_lstm cell in place of the true coordinates, but in your train, i can't find it, you just use 20 true coordinates, and in the your test, same problem

**Comment by quancore** [comment]
I have tried both. For the prediction part, I have used predictions made in observation time but I have been finding out that instead of prediction, I have got the better results using true coordinates for prediction task. You can switch easily by changing the type of list.

**Comment by junjun520416** [comment]
thanks for your great answer. 
another question,in the calculation grid, if the other people don't exist in the current frame,how calculate. In your code,you set the the other people to zero, but if zero exactly is in grid range, how should we do.(my english is pool, Hope you can understand.)

**Comment by quancore** [comment]
I could not understand what is the question exactly however, we are setting all peds that not in current windows to zero in the grid, therefore, their state will not contribute to other neighbor peds.

**Comment by junjun520416** [comment]
I mean that you set the coordinates of the person who did not appear  in the current time to 0, if this  coordinates  is in the range of  neighborhood_size,  it will  set  ped that not in current windows to 1 in the grid

**Comment by quancore** [comment]
The grid has nothing with real positional coordinates. It is a mask. So basically, we are accumulating the neighbor peds for a ped by setting the grid value 1. If a ped is not in a grid of another ped, relevant cell set to 0.

**Comment by bbidong** [comment]
@junjun520416  hi, I finished the train days ago , and could we have a discuss ??
Look forward to your reply !

**Comment by junjun520416** [comment]
> @junjun520416 hi, I finished the train days ago , and could we have a discuss ??
> Look forward to your reply !

my wechat: junjun520416

**Comment by icefengzhe** [comment]
> I have tried both. For the prediction part, I have used predictions made in observation time but I have been finding out that instead of prediction, I have got the better results using true coordinates for prediction task. You can switch easily by changing the type of list.

maybe, it's because you predict the second point by the first input(0, 0),but it's wrong because (0, 0) can predict nothing, and the second point is deadly to last point's prediction...so, i think the loss should be caculated beyond the second point.(my english is poor, sorry, i hope that you can understand me seriously)

**Comment by icefengzhe** [comment]
> > I have tried both. For the prediction part, I have used predictions made in observation time but I have been finding out that instead of prediction, I have got the better results using true coordinates for prediction task. You can switch easily by changing the type of list.
> 
> maybe, it's because you predict the second point by the first input(0, 0),but it's wrong because (0, 0) can predict nothing, and the second point is deadly to last point's prediction...so, i think the loss should be caculated beyond the second point.(my english is poor, sorry, i hope that you can understand me seriously)

maybe should beyond the third point because two points don't have direction information.
