### ISSUE TITLE
Versions of python and pytorch

### ISSUE THREAD

**Issue by joanacfcampos** [quancore/social-lstm#9]
Hi,
Would be possible to share the versions of Python, pytorch, numpy, cuda and other relevant packages used in this implementation?
I am having getting errors when training a model, so I am wondering if this is related to a mismatch of package versions.

**Comment by quancore** [comment]
Because I do not have the setup anymore, I cannot say any exact thing. As far as I remember. Pytorch was PyTorch 0.4.0 and python 3.6,

**Comment by isht7** [comment]
Please mention in readme that this works for python 3 only
